import { getSiteMeta, SITE } from "#/content/site";
import { getLocale, locales, localizeHref } from "#/paraglide/runtime";

/**
 * Absolute, because Open Graph consumers do not resolve relative paths — a root-
 * relative href here silently yields a preview with no image at all.
 *
 * The card itself is generated by scripts/og-image.mjs and deliberately carries no
 * tagline, so one asset serves both locales.
 */
const OG_IMAGE = `${SITE.url}/assets/og-cover.png`;

export function Seo({
	title: pageTitle,
	description: pageDescription,
	path = "/",
}: {
	/** Page name; the site name is appended. Omit on the home page. */
	title?: string;
	description?: string;
	/** Route path, used to build the canonical URL. */
	path?: string;
} = {}) {
	// Home reads "Lipsia Digital — We bring visions to life"; a subpage reads
	// "Team — Lipsia Digital", so the distinguishing word comes first in a tab strip.
	const meta = getSiteMeta();
	const title = pageTitle ? `${pageTitle} — ${SITE.name}` : `${SITE.name} — ${meta.tagline}`;
	const description = pageDescription ?? meta.description;
	const imageAlt = `${SITE.name} — ${meta.tagline}`;
	const locale = getLocale();
	// Every page must advertise its OWN canonical, in its OWN language. `path` is the
	// unlocalised route, so building the URL from it directly made every /en page claim
	// the German URL as canonical — i.e. told search engines the English site was a
	// duplicate. localizeHref applies the same urlPatterns the router uses.
	const url = `${SITE.url}${localizeHref(path, { locale })}`;
	// Reciprocal alternates: each language version points at every version including
	// itself, plus x-default for visitors we have no better guess for.
	const alternates = locales.map((alt) => ({
		locale: alt,
		href: `${SITE.url}${localizeHref(path, { locale: alt })}`,
	}));

	const orgSchema = {
		"@context": "https://schema.org",
		"@type": "Organization",
		name: SITE.name,
		url: SITE.url,
		email: SITE.email,
		telephone: SITE.phone,
		description: meta.description,
		address: {
			"@type": "PostalAddress",
			streetAddress: SITE.street,
			postalCode: "04109",
			addressLocality: "Leipzig",
			addressCountry: "DE",
		},
	};

	return (
		<>
			<title>{title}</title>
			<meta name="description" content={description} />
			<link rel="canonical" href={url} />
			{alternates.map((alt) => (
				<link key={alt.locale} rel="alternate" hrefLang={alt.locale} href={alt.href} />
			))}
			<link rel="alternate" hrefLang="x-default" href={`${SITE.url}/`} />

			{/* Open Graph */}
			<meta property="og:type" content="website" />
			<meta property="og:site_name" content={SITE.name} />
			<meta property="og:title" content={title} />
			<meta property="og:description" content={description} />
			<meta property="og:url" content={url} />
			<meta property="og:locale" content={locale === "de" ? "de_DE" : "en_US"} />
			{/* Dimensions let the unfurler reserve the right box before the image
			    arrives, which is what stops the card reflowing in Slack and LinkedIn. */}
			<meta property="og:image" content={OG_IMAGE} />
			<meta property="og:image:type" content="image/png" />
			<meta property="og:image:width" content="1200" />
			<meta property="og:image:height" content="630" />
			<meta property="og:image:alt" content={imageAlt} />

			{/* Twitter */}
			<meta name="twitter:card" content="summary_large_image" />
			<meta name="twitter:title" content={title} />
			<meta name="twitter:description" content={description} />
			{/* summary_large_image without an image renders as a bare text card, so
			    this tag is what makes the card declaration honest. */}
			<meta name="twitter:image" content={OG_IMAGE} />
			<meta name="twitter:image:alt" content={imageAlt} />

			{/* JSON-LD Organization */}
			<script type="application/ld+json">{JSON.stringify(orgSchema)}</script>
		</>
	);
}
